export const EXTENSION_ACTION = {
  CHANGE_TITLE: 'TAB_TITLE_MANAGER:CHANGE_TITLE',
  GET_SITE_INFO: 'TAB_TITLE_MANAGER:GET_SITE_INFO',
} as const;

export const SYNC_KEY = 'TAB_TITLE_MANAGER:TAB_TITLES';